### ISSUE TITLE
chore: 인증서 발급 이슈 해결 및 https 적용

### ISSUE THREAD

**Issue by dongho108** [dnd-side-project/dnd-8th-5-backend#16]
## As-is
- https 적용이 안됐어요

## To-be
- [x] 인증서 발급 이슈 해결
- [x] https 적용

**Comment by ssssujini99** [comment]
- EC2 보안그룹에 8080포트 개방을 안해줘서 nginx -> web 요청이 안넘어왔음
- root domain(modutime.site) / sub domain(*.modutime.site) 각각 인증서 발급받고 각각 elb로 https 적용시켜줌
- 도메인 연결 후에는 도커 nginx 관련해서 nginx.conf 에서 도메인 추가시켜줌
