### ISSUE TITLE
fix: 실시간 등록 현황 API에서 count 에러를 해결한다

### ISSUE THREAD

**Issue by ssssujini99** [dnd-side-project/dnd-8th-5-backend#62]
## As-is
실시간 등록 현황 API에서 참여자의 count 가 제대로 counting 되고 있지 않습니다

## To-be
- [x] 해당 [날짜/시간] 을 선택한 참여자 수에 맞게 count 값을 반환한다

**Comment by dongho108** [comment]
@ssssujini99 해당 이슈가 왜 발생했는지도 남겨주시면 감사하겠습니다 🙇

**Comment by dongho108** [comment]
오 PR에 남겨주신거 확인했습니다. 이슈에도 남겨주시면 나중에 이슈원인 파악할때 더 편할거같아요!! 나중엔 이슈원인이 PR에 있다는 사실을 모를수도 있으니까요!
