### ISSUE TITLE
fix : deadline 오류를 해결한다

### ISSUE THREAD

**Issue by ssssujini99** [dnd-side-project/dnd-8th-5-backend#73]
## As-is
로컬에서는 제대로 deadline이 설정되는데 배포 서버에서는 deadline이 제대로 설정이 안된다

## To-be
- [ ] 배포서버에서의 deadline이 제대로 설정되도록 한다

**Comment by dongho108** [comment]
애플리케이션 시간 조정 및 ec2 시간 조정으로 해결
